[project]
name = "audio-visualizer"
version = "0.1.0"
description = "Real-time audio visualization from microphone input."
readme = "README.md"
requires-python = "==3.13.*"
dependencies = [
    "matplotlib",
    "numpy",
    "sounddevice",
]

[tool.uv]
package = false
